{% set name = "mo-catnip" %}
{% set version = "1.0.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 65d1c726662069114d4bba6226d621fc0a8d1250b2210ed23763573ab8e87d8c

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python >=3.6

  run:
    - python >=3.6
    - iris
    - numpy
    - six
    - dask
    - matplotlib

test:
  imports:
    - catnip

about:
  home: "https://github.com/MetOffice/CATNIP"
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: "CATNIP package provides methods to simplyfy Iris cube manipulation and analysis"
  doc_url: https://metoffice.github.io/CATNIP/

extra:
  recipe-maintainers:
    - zmaalick
