{% set name = "mo-catnip" %}
{% set version = "1.0.3" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2f619f213fe2bb6d9ba3f68ab8b5784678ed2cf1085f813d1ff721aaad4f9ae8
build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv --no-deps"

requirements:
  host:
    - pip
    - python >=3.6

  run:
    - python >=3.6
    - numpy
    - six
    - scipy
    - matplotlib

test:
  imports:
    - catnip

about:
  home: "https://github.com/MetOffice/CATNIP"
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: "CATNIP package provides methods to simplyfy Iris cube manipulation and analysis"
  doc_url: https://metoffice.github.io/CATNIP/

extra:
  recipe-maintainers:
    - zmaalick
